export const CAPABILITIES = [
  "surat_masuk:view",
  "surat_masuk:create",
  "surat_masuk:edit",
  "surat_masuk:delete",
  "surat_keluar:view",
  "surat_keluar:create",
  "surat_keluar:edit",
  "surat_keluar:delete",
  "surat_keluar:approve",
  "surat_keluar:generate",
  "surat_keluar:assign",
  "disposisi:view",
  "disposisi:create",
  "disposisi:edit",
  "disposisi:sign",
  "disposisi:manage",
  "pegawai:view",
  "pegawai:manage",
  "pejabat:view",
  "pejabat:manage",
  "sertifikat:view",
  "sertifikat:manage",
  "sertifikat:configure",
  "sertifikat:export",
  "jadwal_ujian:view",
  "jadwal_ujian:manage",
  "jadwal_ujian:configure",
  "jadwal_ujian:export",
  "pengaturan:view",
  "pengaturan:manage",
  "roles:manage",
  "divisi:view",
  "divisi:manage",
  "announcement:view",
  "announcement:create",
  "announcement:manage",
  "users:invite",
  "users:manage",
  "nomor_surat:view",
  "nomor_surat:generate",
  "nomor_surat:manage",
  "surat_keputusan:view",
  "surat_keputusan:create",
  "surat_keputusan:edit",
  "surat_keputusan:delete",
  "surat_keputusan:generate",
  "surat_mou:view",
  "surat_mou:create",
  "surat_mou:edit",
  "surat_mou:delete",
  "surat_mou:generate",
  "audit_log:view",
  "audit_log:manage",
  "notification:view",
  "notification:manage",
  "calendar:view",
  "calendar:manage",
  "search:view",
  "profile:view",
  "profile:edit",
] as const;

export type Capability = (typeof CAPABILITIES)[number];

export const CAPABILITY_GROUPS: Array<{
  label: string;
  capabilities: Capability[];
}> = [
  {
    label: "Persuratan",
    capabilities: [
      "surat_masuk:view",
      "surat_masuk:create",
      "surat_masuk:edit",
      "surat_masuk:delete",
      "surat_keluar:view",
      "surat_keluar:create",
      "surat_keluar:edit",
      "surat_keluar:delete",
      "surat_keluar:approve",
      "surat_keluar:generate",
      "surat_keluar:assign",
      "disposisi:view",
      "disposisi:create",
      "disposisi:edit",
      "disposisi:sign",
      "disposisi:manage",
      "nomor_surat:view",
      "nomor_surat:generate",
      "nomor_surat:manage",
      "surat_keputusan:view",
      "surat_keputusan:create",
      "surat_keputusan:edit",
      "surat_keputusan:delete",
      "surat_keputusan:generate",
      "surat_mou:view",
      "surat_mou:create",
      "surat_mou:edit",
      "surat_mou:delete",
      "surat_mou:generate",
    ],
  },
  {
    label: "Organisasi",
    capabilities: [
      "pegawai:view",
      "pegawai:manage",
      "pejabat:view",
      "pejabat:manage",
      "divisi:view",
      "divisi:manage",
      "users:invite",
      "users:manage",
      "roles:manage",
    ],
  },
  {
    label: "Komunikasi",
    capabilities: [
      "announcement:view",
      "announcement:create",
      "announcement:manage",
      "notification:view",
      "notification:manage",
      "calendar:view",
      "calendar:manage",
      "search:view",
      "profile:view",
      "profile:edit",
    ],
  },
  {
    label: "Sertifikat & Jadwal",
    capabilities: [
      "sertifikat:view",
      "sertifikat:manage",
      "sertifikat:configure",
      "sertifikat:export",
      "jadwal_ujian:view",
      "jadwal_ujian:manage",
      "jadwal_ujian:configure",
      "jadwal_ujian:export",
    ],
  },
  {
    label: "Sistem",
    capabilities: [
      "pengaturan:view",
      "pengaturan:manage",
      "audit_log:view",
      "audit_log:manage",
    ],
  },
];

export const CAPABILITY_LABELS: Record<Capability, string> = {
  "surat_masuk:view": "Lihat surat masuk",
  "surat_masuk:create": "Buat surat masuk",
  "surat_masuk:edit": "Ubah surat masuk",
  "surat_masuk:delete": "Hapus surat masuk",
  "surat_keluar:view": "Lihat surat keluar",
  "surat_keluar:create": "Buat surat keluar",
  "surat_keluar:edit": "Ubah surat keluar",
  "surat_keluar:delete": "Hapus surat keluar",
  "surat_keluar:approve": "Setujui surat keluar",
  "surat_keluar:generate": "Generate surat keluar",
  "surat_keluar:assign": "Assign surat keluar",
  "disposisi:view": "Lihat disposisi",
  "disposisi:create": "Buat disposisi",
  "disposisi:edit": "Ubah disposisi",
  "disposisi:sign": "Tanda tangan disposisi",
  "disposisi:manage": "Kelola disposisi",
  "pegawai:view": "Lihat pegawai",
  "pegawai:manage": "Kelola pegawai",
  "pejabat:view": "Lihat pejabat",
  "pejabat:manage": "Kelola pejabat",
  "sertifikat:view": "Lihat sertifikat",
  "sertifikat:manage": "Kelola sertifikat",
  "sertifikat:configure": "Konfigurasi sertifikat",
  "sertifikat:export": "Export sertifikat",
  "jadwal_ujian:view": "Lihat jadwal ujian",
  "jadwal_ujian:manage": "Kelola jadwal ujian",
  "jadwal_ujian:configure": "Konfigurasi jadwal ujian",
  "jadwal_ujian:export": "Export jadwal ujian",
  "pengaturan:view": "Lihat pengaturan",
  "pengaturan:manage": "Kelola pengaturan",
  "roles:manage": "Kelola role",
  "divisi:view": "Lihat divisi",
  "divisi:manage": "Kelola divisi",
  "announcement:view": "Lihat pengumuman",
  "announcement:create": "Buat pengumuman",
  "announcement:manage": "Kelola pengumuman",
  "users:invite": "Undang user",
  "users:manage": "Kelola user",
  "nomor_surat:view": "Lihat nomor surat",
  "nomor_surat:generate": "Generate nomor surat",
  "nomor_surat:manage": "Kelola nomor surat",
  "surat_keputusan:view": "Lihat surat keputusan",
  "surat_keputusan:create": "Buat surat keputusan",
  "surat_keputusan:edit": "Ubah surat keputusan",
  "surat_keputusan:delete": "Hapus surat keputusan",
  "surat_keputusan:generate": "Generate surat keputusan",
  "surat_mou:view": "Lihat surat MOU",
  "surat_mou:create": "Buat surat MOU",
  "surat_mou:edit": "Ubah surat MOU",
  "surat_mou:delete": "Hapus surat MOU",
  "surat_mou:generate": "Generate surat MOU",
  "audit_log:view": "Lihat audit log",
  "audit_log:manage": "Kelola audit log",
  "notification:view": "Lihat notifikasi",
  "notification:manage": "Kelola notifikasi",
  "calendar:view": "Lihat kalender",
  "calendar:manage": "Kelola kalender",
  "search:view": "Gunakan pencarian",
  "profile:view": "Lihat profil",
  "profile:edit": "Ubah profil",
};

export const DEFAULT_ROLE_CAPABILITIES: Record<
  "staff" | "pejabat" | "viewer",
  Capability[]
> = {
  staff: [
    "surat_masuk:view",
    "surat_masuk:create",
    "surat_masuk:edit",
    "surat_keluar:view",
    "surat_keluar:create",
    "surat_keluar:edit",
    "disposisi:view",
    "disposisi:edit",
    "disposisi:manage",
    "pegawai:view",
    "pejabat:view",
    "sertifikat:view",
    "sertifikat:manage",
    "sertifikat:export",
    "jadwal_ujian:view",
    "jadwal_ujian:manage",
    "jadwal_ujian:export",
    "announcement:view",
    "divisi:view",
    "audit_log:manage",
    "notification:view",
    "notification:manage",
    "calendar:view",
    "calendar:manage",
    "search:view",
    "profile:view",
    "profile:edit",
  ],
  pejabat: [
    "surat_masuk:view",
    "surat_masuk:edit",
    "surat_keluar:view",
    "surat_keluar:create",
    "surat_keluar:edit",
    "surat_keluar:approve",
    "surat_keluar:generate",
    "surat_keluar:assign",
    "disposisi:view",
    "disposisi:create",
    "disposisi:edit",
    "disposisi:sign",
    "disposisi:manage",
    "pegawai:view",
    "pejabat:view",
    "jadwal_ujian:view",
    "announcement:view",
    "divisi:view",
    "nomor_surat:view",
    "nomor_surat:generate",
    "nomor_surat:manage",
    "surat_keputusan:view",
    "surat_keputusan:create",
    "surat_keputusan:edit",
    "surat_keputusan:generate",
    "surat_mou:view",
    "surat_mou:create",
    "surat_mou:edit",
    "surat_mou:generate",
    "notification:view",
    "notification:manage",
    "calendar:view",
    "calendar:manage",
    "search:view",
    "profile:view",
    "profile:edit",
  ],
  viewer: [
    "surat_masuk:view",
    "surat_keluar:view",
    "disposisi:view",
    "pegawai:view",
    "pejabat:view",
    "sertifikat:view",
    "jadwal_ujian:view",
    "announcement:view",
    "divisi:view",
    "notification:view",
    "notification:manage",
    "calendar:view",
    "calendar:manage",
    "search:view",
    "profile:view",
    "profile:edit",
  ],
};

export function isCapability(value: string): value is Capability {
  return (CAPABILITIES as readonly string[]).includes(value);
}
